baseURL: "https://chagarr.org/hugo-website/" 
title: Charles Garrisi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: News
          url: 
          weight: 1
        - name: Papers
          url: 
          weight: 2
        - name: Talks
          url: 
          weight: 3
        - name: Teaching
          url: 
          weight: 4
        - name: Blog
          url: https://en.wikipedia.org/wiki/Kalman_filter
          weight: 5

params:
    description: "This website hosts Charles Garrisi's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Charles Garrisi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "November 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Charles Garrisi
          subtitle: "I am a PhD student in Applied Mathematics at Mines Paris - PSL, under the supervision of Fran√ßois Pacaud and Welington de Oliveira. My research explores large-scale optimization and data-driven decision-making under uncertainty."
          imageUrl: "id.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: News
              url: news/
            - name: Blog
              url: blog/
            - name: Papers
              url: paper/
            - name: Talks
              url: talks/
            - name: Teaching
              url: teaching/
    
          

    socialIcons:
        - name: CV
          url: CV.pdf
        - name: Email
          url: mailto:charles.garrisi@minesparis.psl.eu
        - name: Location
          url: location/
        - name: Google Scholar
          url: 
        - name: GitHub
          url: https://github.com/chagarr

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Charles Garrisi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
